### ISSUE TITLE
Progress bar click + auto play next?

### ISSUE THREAD

**Issue by costheme** [Irubataru/tiny-html-audio-player#4]
Hi, great plugin, i love it but it misses 2 features that are very useful for audio players:

1. Is there any way we can change the song progress by clicking the progress bar?

2. Any option for auto-play next song from an existing playlist container?

Thank you !

**Comment by Irubataru** [comment]
Thanks for liking the plugin, I am sort of surprised someone found this. This was a pet project I started just to see if I was able to make a "web plugin" (or whatever you would call something like this), and I never really expected anyone to see it.

As for your suggestions:

1. That should be fairly easily doable, I think I never did that because it was hard to define where such a click should register, but I guess that if you simply say "anything that isn't a button will affect progress", then it isn't too hard.

2. If I were to implement that I would also have to add some sort of plugin config because I would personally not want that behaviour for the site I used it on. It wasn't intended to be a full audio-player with multiple tracks etc, I made it because I wanted a one-song audio player. Sort of the difference between putting one image on your site vs. an album. As almost all other web audio players I found was the latter, I made this to have the former.

But they are good suggestions, and if I ever feel like working on this project again I'll try to implement them. However I can't guarantee that this will be anytime soon, so you should either fork/clone this and implement it yourself, or look around, there are tons of open source audio players.

**Comment by Irubataru** [comment]
So, I added a seek functionality in v0.2.0, however I do not believe I will address the second point anytime soon. Anyway, thanks again for the suggestions, and if you for some reason still want to look at it you can try out the seek functionality and see if it works as expected.
